### ISSUE TITLE
Routing

### ISSUE THREAD

**Issue by nicrocs** [vacas5/marvel#4]
So far, we've talked about showing characters and series. I'm planning on implementing react-router. I've used it before and it works well. 

Are we showing characters on the index?

Just wondering what the routes should be at this point. 
So we might have a structure that looks like this:

```
-index
    -characters/<letter> (which <a> doubles as the index)
          -characters/<id>/profile
    -series/<letter>
          -series/<id>/detail
```

**Comment by vacas5** [comment]
yeah I think characters and series. There is also an "events" endpoint. Let's start simple though with those two. Characters can be the default route.
